### ISSUE TITLE
Eliminar comentarios

### ISSUE THREAD

**Issue by Nidev-lab** [Mausach/proyectoFinalRollingCodeBackend#1]
Buenas! como va? encontre algunos comentarios en el codigo,

![image](https://github.com/Mausach/proyectoFinalRollingCodeBackend/assets/53904695/9817deb2-ce0f-4fed-98dd-85792eb06063)

Recuerden, los comentarios no estan vistos como una buena practica , pero en si el codigo comentado es mucho menos aceptado.

Cualquier cosita podes contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode****

**Comment by Mausach** [comment]
ya se realizo esta modificación
